// WP2 测试：core/src/mo2fmt.cpp（MO2 磁盘格式解析）
#include <chrono>
#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <system_error>
#include <vector>

#include "minitest.hpp"

#include "mol/mo2fmt.hpp"

namespace fs = std::filesystem;

namespace {

// ---- 文件系统辅助 ---------------------------------------------------------
// 每个测试一个 /tmp 下的唯一子目录，RAII 清理。
struct TempDir {
    fs::path path;
    explicit TempDir(const char* tag) {
        static std::uint64_t counter = 0;
        const auto now = std::chrono::duration_cast<std::chrono::nanoseconds>(
                            std::chrono::system_clock::now().time_since_epoch())
                            .count();
        ++counter;
        std::error_code ec;
        const fs::path base = fs::temp_directory_path(ec);
        CHECK(!ec);
        CHECK(base.generic_string().rfind("/tmp", 0) == 0);
        path = base / ("mo2fmt_test_" + std::string(tag) + "_" + std::to_string(now) + "_" +
                       std::to_string(counter));
        fs::create_directories(path, ec);
        CHECK(!ec);
        CHECK(fs::is_directory(path));
    }
    ~TempDir() {
        std::error_code ec;
        fs::remove_all(path, ec);
    }
    TempDir(const TempDir&) = delete;
    TempDir& operator=(const TempDir&) = delete;
};

fs::path write_bytes(const fs::path& p, std::string_view content) {
    std::ofstream out(p, std::ios::binary | std::ios::trunc);
    CHECK(static_cast<bool>(out));
    out.write(content.data(), static_cast<std::streamsize>(content.size()));
    out.close();
    CHECK(!out.fail());
    return p;
}

std::string read_bytes(const fs::path& p) {
    std::ifstream in(p, std::ios::binary);
    CHECK(static_cast<bool>(in));
    return std::string(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}

// 目录条目名，显式排序保证确定性。
std::vector<std::string> dir_entries(const fs::path& d) {
    std::vector<std::string> names;
    std::error_code ec;
    for (const auto& e : fs::directory_iterator(d, ec)) {
        names.push_back(e.path().filename().string());
    }
    CHECK(!ec);
    std::sort(names.begin(), names.end());
    return names;
}

template <class F>
bool throws_runtime(F&& f) {
    try {
        f();
    } catch (const std::runtime_error&) {
        return true;
    }
    return false;
}

// ---- 结构辅助 -------------------------------------------------------------
mol::ModEntry make_mod(std::string_view name, bool enabled, bool separator = false) {
    mol::ModEntry e;
    e.name.assign(name.begin(), name.end());
    e.enabled = enabled;
    e.separator = separator;
    return e;
}

mol::PluginEntry make_plugin(std::string_view name, bool enabled) {
    mol::PluginEntry e;
    e.name.assign(name.begin(), name.end());
    e.enabled = enabled;
    return e;
}

std::string to_std(const mol::string& s) { return std::string(s.begin(), s.end()); }

// wine_to_unix 的便捷包装：走默认 memory_resource，转成 std::string 便于比对。
std::string wu(std::string_view p, std::string_view pfx) {
    return to_std(mol::wine_to_unix(p, pfx));
}

// ###name[enabled]/... 便于一行比对全部字段。
std::string dump_mods(const mol::vector<mol::ModEntry>& v) {
    std::string s;
    for (const auto& e : v) {
        s += '|';
        s += e.enabled ? '+' : '-';
        s += std::string(e.name.begin(), e.name.end());
        if (e.separator) {
            s += "%SEP";
        }
    }
    return s;
}

std::string dump_plugins(const mol::vector<mol::PluginEntry>& v) {
    std::string s;
    for (const auto& e : v) {
        s += '|';
        s += e.enabled ? '+' : '-';
        s += std::string(e.name.begin(), e.name.end());
    }
    return s;
}

std::string join(const mol::vector<mol::string>& v) {
    std::string s;
    for (const auto& e : v) {
        s += '|';
        s += std::string(e.begin(), e.end());
    }
    return s;
}

std::string opt_str(const std::optional<mol::string>& v) {
    if (!v) {
        return "<nullopt>";
    }
    return std::string(v->begin(), v->end());
}

// ===========================================================================
// modlist.txt
// ===========================================================================
TEST(modlist_read_reverses_and_skips_unmanaged) {
    TempDir dir("modlist");
    const fs::path p = write_bytes(dir.path / "modlist.txt",
        "# This file was automatically generated by Mod Organizer.\n"
        "+Alpha\n"                 // 最高优先级（文件第一条）
        "\n"
        "-Beta\n"
        "*ForeignMod\n"            // 未管理：跳过
        "# a comment\n"
        "+Gamma\n");               // 最低优先级

    const auto v = mol::read_modlist(p.string());
    // 文件顺序反转后（低→高）：Gamma, Beta, Alpha
    CHECK_EQ(dump_mods(v), std::string("|+Gamma|-Beta|+Alpha"));
    CHECK_EQ(v.size(), 3u);
    CHECK(v[0].enabled);    // Gamma
    CHECK(!v[1].enabled);  // Beta
    CHECK(v[2].enabled);    // Alpha
}

TEST(modlist_read_crlf_and_bom) {
    TempDir dir("modlist");
    const fs::path p = write_bytes(dir.path / "modlist.txt",
        "\xEF\xBB\xBF# header\r\n"
        "+Alpha\r\n"
        "-Beta\r\n"
        "# comment\r\n"
        "\r\n"
        "*Foreign\r\n");
    const auto v = mol::read_modlist(p.string());
    CHECK_EQ(dump_mods(v), std::string("|-Beta|+Alpha"));
    CHECK_EQ(v.size(), 2u);
    CHECK(!v[0].enabled);
    CHECK(v[1].enabled);
}

TEST(modlist_read_empty_variants) {
    TempDir dir("modlist");
    // 不存在
    {
        const fs::path missing = dir.path / "does_not_exist" / "modlist.txt";
        const auto v = mol::read_modlist(missing.string());
        CHECK(v.empty());
    }
    // 空文件
    {
        const fs::path p = write_bytes(dir.path / "empty.txt", "");
        const auto v = mol::read_modlist(p.string());
        CHECK(v.empty());
    }
    // 只有注释/空行
    {
        const fs::path p = write_bytes(dir.path / "comments.txt", "# only\n\n# still\n");
        const auto v = mol::read_modlist(p.string());
        CHECK(v.empty());
    }
}

TEST(modlist_read_separator_flag) {
    TempDir dir("modlist");
    const fs::path p = write_bytes(dir.path / "modlist.txt",
        "-Body_Sep__separator\n"
        "+Head_separator\n"
        "-separator\n"     // 不以 _separator 结尾
        "+Exactly_separato\n");
    const auto v = mol::read_modlist(p.string());
    CHECK_EQ(dump_mods(v),
             std::string("|+Exactly_separato|-separator|+Head_separator%SEP|-Body_Sep__separator%SEP"));
    CHECK_EQ(v.size(), 4u);
    CHECK(!v[0].separator);  // Exactly_separato
    CHECK(!v[1].separator);  // separator
    CHECK(v[2].separator);    // Head_separator
    CHECK(v[3].separator);    // Body_Sep__separator
}

TEST(modlist_write_roundtrip_atomic) {
    TempDir dir("modlist");
    const fs::path p = dir.path / "modlist.txt";

    mol::vector<mol::ModEntry> low_to_high;
    low_to_high.push_back(make_mod("Alpha", true));
    low_to_high.push_back(make_mod("Beta", false));
    low_to_high.push_back(make_mod("Head_separator", true, true));
    mol::write_modlist(p.string(), low_to_high);

    // 原子写：目录里只有目标文件，无临时文件残留。
    const auto entries = dir_entries(dir.path);
    CHECK_EQ(entries.size(), 1u);
    if (!entries.empty()) {
        CHECK_EQ(entries[0], std::string("modlist.txt"));
    }

    const std::string expected =
        "# This file was automatically generated by Mod Organizer.\n"
        "+Head_separator\n"   // 最高优先级写最前
        "-Beta\n"
        "+Alpha\n";
    CHECK_EQ(read_bytes(p), expected);

    const auto back = mol::read_modlist(p.string());
    CHECK_EQ(dump_mods(back), std::string("|+Alpha|-Beta|+Head_separator%SEP"));
    CHECK_EQ(back.size(), 3u);
}

TEST(modlist_write_overwrites_existing) {
    TempDir dir("modlist");
    const fs::path p = dir.path / "modlist.txt";
    write_bytes(p, "stale content that must be replaced\n");

    mol::vector<mol::ModEntry> low_to_high;
    low_to_high.push_back(make_mod("Only", true));
    mol::write_modlist(p.string(), low_to_high);

    const auto entries = dir_entries(dir.path);
    CHECK_EQ(entries.size(), 1u);
    CHECK_EQ(read_bytes(p), std::string("# This file was automatically generated by Mod Organizer.\n+Only\n"));
    const auto back = mol::read_modlist(p.string());
    CHECK_EQ(dump_mods(back), std::string("|+Only"));
}

TEST(modlist_write_empty_list) {
    TempDir dir("modlist");
    const fs::path p = dir.path / "modlist.txt";
    std::span<const mol::ModEntry> empty;
    mol::write_modlist(p.string(), empty);
    CHECK_EQ(read_bytes(p), std::string("# This file was automatically generated by Mod Organizer.\n"));
    CHECK_EQ(dir_entries(dir.path).size(), 1u);
    CHECK(mol::read_modlist(p.string()).empty());
}

TEST(modlist_write_missing_directory_throws) {
    TempDir dir("modlist");
    const fs::path p = dir.path / "no_such_dir" / "modlist.txt";
    std::span<const mol::ModEntry> empty;
    CHECK(throws_runtime([&] { mol::write_modlist(p.string(), empty); }));
}

// ===========================================================================
// plugins.txt
// ===========================================================================
TEST(plugins_txt_read_basic) {
    TempDir dir("plugins");
    const fs::path p = write_bytes(dir.path / "plugins.txt",
        "# This file was automatically generated by Mod Organizer.\n"
        "*Dawnguard.esm\n"
        "Update.esm\n"
        "\n"
        "*Skyrim.esm\n");
    const auto v = mol::read_plugins_txt(p.string());
    CHECK_EQ(dump_plugins(v), std::string("|+Dawnguard.esm|-Update.esm|+Skyrim.esm"));
    CHECK_EQ(v.size(), 3u);
    CHECK(v[0].enabled);
    CHECK(!v[1].enabled);
    CHECK(v[2].enabled);
}

TEST(plugins_txt_read_empty_variants) {
    TempDir dir("plugins");
    {
        const auto v = mol::read_plugins_txt((dir.path / "nope.txt").string());
        CHECK(v.empty());
    }
    {
        const fs::path p = write_bytes(dir.path / "empty.txt", "");
        CHECK(mol::read_plugins_txt(p.string()).empty());
    }
    {
        const fs::path p = write_bytes(dir.path / "comments.txt", "# head\n\n# again\n*\n");
        CHECK(mol::read_plugins_txt(p.string()).empty());
    }
    {
        // CRLF + BOM：plugins.txt 中禁用条目不带任何前缀
        const fs::path p = write_bytes(dir.path / "crlf.txt", "\xEF\xBB\xBF" "*One.esp\r\nTwo.esp\r\n");
        CHECK_EQ(dump_plugins(mol::read_plugins_txt(p.string())), std::string("|+One.esp|-Two.esp"));
    }
}

TEST(plugins_txt_write_roundtrip_atomic) {
    TempDir dir("plugins");
    const fs::path p = dir.path / "plugins.txt";

    mol::vector<mol::PluginEntry> v;
    v.push_back(make_plugin("Skyrim.esm", true));
    v.push_back(make_plugin("Update.esm", false));
    mol::write_plugins_txt(p.string(), v);

    const auto entries = dir_entries(dir.path);
    CHECK_EQ(entries.size(), 1u);
    if (!entries.empty()) {
        CHECK_EQ(entries[0], std::string("plugins.txt"));
    }
    CHECK_EQ(read_bytes(p),
             std::string("# This file was automatically generated by Mod Organizer.\n"
                         "*Skyrim.esm\n"
                         "Update.esm\n"));
    CHECK_EQ(dump_plugins(mol::read_plugins_txt(p.string())), std::string("|+Skyrim.esm|-Update.esm"));
}

TEST(plugins_txt_write_preserves_order) {
    TempDir dir("plugins");
    const fs::path p = dir.path / "plugins.txt";
    mol::vector<mol::PluginEntry> v;
    v.push_back(make_plugin("B.esp", false));
    v.push_back(make_plugin("A.esp", true));
    mol::write_plugins_txt(p.string(), v);
    const auto back = mol::read_plugins_txt(p.string());
    CHECK_EQ(dump_plugins(back), std::string("|-B.esp|+A.esp"));  // 顺序即读取顺序
}

// ===========================================================================
// loadorder.txt
// ===========================================================================
TEST(loadorder_read_basic) {
    TempDir dir("loadorder");
    const fs::path p = write_bytes(dir.path / "loadorder.txt",
        "# This file was automatically generated by Mod Organizer.\n"
        "Skyrim.esm\r\n"
        "Update.esm\r\n"
        "\r\n"
        "Dawnguard.esm\r\n");
    const auto v = mol::read_loadorder_txt(p.string());
    CHECK_EQ(join(v), std::string("|Skyrim.esm|Update.esm|Dawnguard.esm"));
}

TEST(loadorder_read_empty_variants) {
    TempDir dir("loadorder");
    CHECK(mol::read_loadorder_txt((dir.path / "nope.txt").string()).empty());
    {
        const fs::path p = write_bytes(dir.path / "empty.txt", "");
        CHECK(mol::read_loadorder_txt(p.string()).empty());
    }
    {
        const fs::path p = write_bytes(dir.path / "comments.txt", "# only\n\n");
        CHECK(mol::read_loadorder_txt(p.string()).empty());
    }
    {
        const fs::path p = write_bytes(dir.path / "bom.txt", "\xEF\xBB\xBF" "A.esp\n");
        const auto v = mol::read_loadorder_txt(p.string());
        CHECK_EQ(v.size(), 1u);
        if (!v.empty()) {
            CHECK_EQ(to_std(v[0]), std::string("A.esp"));
        }
    }
}

// ===========================================================================
// Ini
// ===========================================================================
TEST(ini_sections_casefold_comments) {
    TempDir dir("ini");
    const fs::path p = write_bytes(dir.path / "custom.ini",
        "; semicolon comment\n"
        "# hash comment\n"
        "[General]\n"
        "Language=en\n"
        "  Spaced   =   value with spaces   \n"
        "Empty=\n"
        "\n"
        "[AnotherSection]\n"
        "key=value42\n");

    const mol::Ini ini = mol::Ini::load(p.string());
    CHECK_EQ(opt_str(ini.get("General", "language")), std::string("en"));
    CHECK_EQ(opt_str(ini.get("GENERAL", "LANGUAGE")), std::string("en"));
    CHECK_EQ(opt_str(ini.get("general", "Language")), std::string("en"));
    CHECK_EQ(opt_str(ini.get("General", "spaced")), std::string("value with spaces"));
    CHECK_EQ(opt_str(ini.get("General", "empty")), std::string(""));  // 空值是有效值
    CHECK_EQ(opt_str(ini.get("AnotherSection", "key")), std::string("value42"));
    CHECK_EQ(opt_str(ini.get("Missing", "key")), std::string("<nullopt>"));
    CHECK_EQ(opt_str(ini.get("General", "nosuchkey")), std::string("<nullopt>"));
}

TEST(ini_keys_before_first_section) {
    const mol::Ini ini = mol::Ini::parse(
        "globalKey=1\n"
        "[General]\n"
        "a=b\n");
    // 空串 section 表示 [General] 之前的无区段键
    CHECK_EQ(opt_str(ini.get("", "GLOBALKEY")), std::string("1"));
    CHECK_EQ(opt_str(ini.get("General", "a")), std::string("b"));
    CHECK_EQ(opt_str(ini.get("General", "globalKey")), std::string("<nullopt>"));
    CHECK_EQ(opt_str(ini.get("", "a")), std::string("<nullopt>"));
}

TEST(ini_bytearray_and_backslashes) {
    const mol::Ini ini = mol::Ini::parse(
        "[General]\n"
        "raw=@Variant(\\x00)\n"
        "bytes=@ByteArray(ab\\cd)\n"
        "empty=@ByteArray()\n"
        "path=C:\\Users\\me\n"
        "home=Z:\\\\home\\\\me\n"
        "eq=a=b=c\n");
    CHECK_EQ(opt_str(ini.get("General", "raw")), std::string("@Variant(\\x00)"));  // 原样保留
    CHECK_EQ(opt_str(ini.get("General", "bytes")), std::string("ab\\cd"));         // 去壳
    CHECK_EQ(opt_str(ini.get("General", "empty")), std::string(""));               // 空壳
    CHECK_EQ(opt_str(ini.get("General", "path")), std::string("C:\\Users\\me"));   // 反斜杠不折叠
    CHECK_EQ(opt_str(ini.get("General", "home")), std::string("Z:\\\\home\\\\me"));
    CHECK_EQ(opt_str(ini.get("General", "eq")), std::string("a=b=c"));             // 按第一个 '=' 切
}

TEST(ini_duplicate_keys_last_wins) {
    const mol::Ini ini = mol::Ini::parse(
        "[S]\n"
        "k=first\n"
        "K=second\n"
        "j=1\n"
        "j=2\n"
        "[S]\n"
        "newkey=3\n");
    CHECK_EQ(opt_str(ini.get("s", "K")), std::string("second"));
    CHECK_EQ(opt_str(ini.get("S", "k")), std::string("second"));
    CHECK_EQ(opt_str(ini.get("S", "J")), std::string("2"));
    // 同名区段第二次出现：键仍可读
    CHECK_EQ(opt_str(ini.get("S", "newkey")), std::string("3"));
}

TEST(ini_empty_and_missing) {
    CHECK_EQ(opt_str(mol::Ini::parse("").get("General", "x")), std::string("<nullopt>"));
    CHECK_EQ(opt_str(mol::Ini::parse("\n\n   \n").get("", "x")), std::string("<nullopt>"));
    {
        TempDir dir("ini");
        const mol::Ini ini = mol::Ini::load((dir.path / "nope.ini").string());
        CHECK_EQ(opt_str(ini.get("General", "x")), std::string("<nullopt>"));
    }
}

TEST(ini_roundtrip_load_from_file) {
    TempDir dir("ini");
    const fs::path p = write_bytes(dir.path / "skyrimprefs.ini",
        "\xEF\xBB\xBF[General]\n"
        "sLanguage=en\n"
        "uGridsToLoad=5\r\n"
        "[Display]\n"
        "bFull Screen=@ByteArray(00)\n");
    const mol::Ini ini = mol::Ini::load(p.string());
    CHECK_EQ(opt_str(ini.get("General", "slanguage")), std::string("en"));
    // 键名含空格：casefold 不影响空格本身
    CHECK_EQ(opt_str(ini.get("display", "BFull Screen")), std::string("00"));
    CHECK_EQ(opt_str(ini.get("DISPLAY", "bfull screen")), std::string("00"));
}

// ===========================================================================
// wine_to_unix
// ===========================================================================
TEST(wine_to_unix_cases) {
    const std::string pfx = "/prefix";
    CHECK_EQ(wu("Z:\\home\\u\\x", pfx), std::string("/home/u/x"));
    CHECK_EQ(wu("z:\\home", pfx), std::string("/home"));
    CHECK_EQ(wu("C:\\Users\\u", pfx), std::string("/prefix/drive_c/Users/u"));
    CHECK_EQ(wu("c:\\users\\u", pfx), std::string("/prefix/drive_c/users/u"));
    CHECK_EQ(wu("C:", pfx), std::string("/prefix/drive_c"));
    CHECK_EQ(wu("C:\\", pfx), std::string("/prefix/drive_c"));
    CHECK_EQ(wu("D:\\Games", pfx), std::string("/prefix/dosdevices/d:/Games"));
    CHECK_EQ(wu("d:", pfx), std::string("/prefix/dosdevices/d:"));
    CHECK_EQ(wu("C:\\a\\..\\b", pfx), std::string("/prefix/drive_c/a/../b"));  // 不折叠 ..
    CHECK_EQ(wu("/already/a/unix/path", pfx), std::string("/already/a/unix/path"));
    // 双反斜杠视作分隔符
    CHECK_EQ(wu("C:\\\\Users\\\\u", pfx), std::string("/prefix/drive_c/Users/u"));
    CHECK_EQ(wu("Z:\\\\home", pfx), std::string("/home"));
    // 单个正斜杠分隔符
    CHECK_EQ(wu("C:/Users/u", pfx), std::string("/prefix/drive_c/Users/u"));
}

}  // namespace
